name: graphql_codegen_config
description: "Config library for graphql_codegen"
version: 0.1.0
homepage: https://github.com/heftapp/graphql_codegen/tree/main/graphql_codegen_config
repository: https://github.com/heftapp/graphql_codegen/tree/main/graphql_codegen_config

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
